app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', 'FrontController@showWelcome');
Route::get('/admin/dashboard', 'AdminController@index');
Route::get('/index-tables', 'FrontController@loadHomeTables');
Route::get('/roster', 'RosterController@front_index');
Route::get('/staff', 'FrontController@showStaff');
Route::get('/weather', 'FrontController@showWeather');
Route::get('/documents', 'FrontController@showDocuments');
Route::get('/scenery', 'FrontController@showScenery');
Route::get('/stats/{year?}/{month?}', 'FrontController@showStats');
Route::get('/event/{id}', 'FrontController@showEvents');
Route::resource('/feedback', 'FeedbackController');
Route::get('/login', 'RosterController@loginv2');
Route::get('/test-login/{cid}', 'RosterController@testLogin');
// Route::get('/login2', 'RosterController@loginv2');
Route::get('/visit', 'FrontController@showVisit');
Route::post('/visit', 'AdminController@saveVisit');
Route::get('/test', 'FrontController@showTest');
Route::get('/comms', 'FrontController@showComms');
Route::get('/log', 'AdminController@showUserLog');
Route::get('/log/{id}', 'AdminController@log');
Route::get('/privacy', 'FrontController@showPrivacy');


Route::get('/sendemail', 'FrontController@sendEmail');
Route::get('/airports', 'FrontController@showAirportList');
Route::get('/airports/{id}', 'FrontController@getAirport');
Route::get('/runways', 'FrontController@showRunways');

Route::get('/admin/announcements', 'AdminController@showAnnouncements');
Route::post('/admin/announcements/{id}/update', 'AdminController@updateAnnouncements');

Route::get('/trainingcenter', 'TrainingCenter@showIndex');
Route::get('/trainingcenter/{view}', 'TrainingCenter@showTraining')->where('view', '.*');

Route::group(['before' => 'auth'], function(){
    Route::get('/ids', 'IDSController@showIDS');

    Route::get('/admin/email-password', 'EmailController@index');
    Route::post('/admin/email-password', 'EmailController@setPassword');

    //user routes
    Route::get('/logout', 'RosterController@logout');
    Route::get('/profile/{id?}', 'FrontController@showProfile');
    Route::get('/atcast', 'FrontController@showATCast');
    Route::post('/event/{id}/request', 'EventController@requestPosition');
    Route::post('/event/{id}/unassign', 'EventController@selfUnnasign');
    Route::post('/event/{id}/assignPositionManual', 'EventController@assignPositionManual');
    //Route::post('/event/uploadBanner','EventController@uploadBanner');
    Route::get('/admin/announcements', 'AdminController@showAnnouncements');
    Route::post('/admin/announcements/{id}/update', 'AdminController@updateAnnouncements');

/*
    Route::post('/admin/broadcast/create', 'BroadcastController@store');
    Route::resource('/admin/broadcast', 'BroadcastController');
*/
    Route::get('/admin/activitylog', 'AdminController@showActivityLog');
    Route::get('/admin/activitylog/filter/{id}', 'AdminController@filterActivityLog');
    
    //training routes
    Route::get('/training', 'TrainingController@showRequests');
    Route::delete('/training/{id}/delete', 'TrainingController@cancelSession');
    Route::get('/training/exams', 'TrainingController@showExams');
    Route::get('/training/notes', 'TrainingController@showNotes');
    Route::get('/training/note/{id}', 'TrainingController@showNote');
    Route::get('training/pexams', 'ExamController@showPendingPracticalExams');
    Route::get('/training/pexams/history', 'ExamController@showCompletedPracticalExams');
    Route::get('/training/texams', 'ExamController@showPendingTheoryExams');
    Route::get('/training/texams/history', 'ExamController@showCompletedTheoryExams');
    Route::get('/training/mentoravail', 'TrainingController@showMentAvail');
    Route::post('/training/mentoravail', 'TrainingController@saveSession');

    Route::group(['before' => 'events'], function(){
        Route::resource('/admin/events', 'EventController');
        Route::post('/admin/events/{id}/sort_positions', 'EventController@resortPositions');
        Route::post('/admin/events/{id}/position', 'EventController@createPosition');
        Route::delete('/admin/events/{event_id}/position/{position_id}', 'EventController@deletePosition');
        Route::post('/admin/events/{event_id}/position/{position_id}/unassign', 'EventController@unassignPosition');
        Route::post('/admin/events/position/{position_id}/assign/{controller_id}', 'EventController@assignPosition');
        Route::delete('/admin/events/posreq/{id}/delete', 'EventController@deleteRequest');
        Route::post('/admin/events/{id}/active', 'EventController@setEventActive');
        Route::post('/admin/events/{id}/hidden', 'EventController@setEventHidden');
    });

    Route::group(['before' => 'docs'], function(){
        Route::resource('/admin/docs', 'DocumentController', ['except' => ['show']]);
    });

    Route::group(['before' => 'snrstaff'], function(){
        Route::get('/admin/mentorhist', 'AdminController@showMentorHistory');
        Route::get('/api/roster', 'ApiController@roster');
        Route::get('/admin/rostertidy', 'AdminController@showRosterCleanup');
        Route::post('/admin/rostertidy/{id}/sendwarning', 'AdminController@sendWarning');
    });

    Route::group(['before' => 'scenery'], function(){
        Route::resource('/admin/scenery', 'SceneryController');
        Route::resource('/admin/comms', 'CommsController', ['except' => ['show']]);
        Route::get('/admin/comms/atis', 'CommsController@ATISindex');
        Route::post('/admin/comms/atis/{id}/store', 'CommsController@storeATIS');
        Route::post('/admin/comms/atis/{id}/update', 'CommsController@updateATIS');
        Route::delete('/admin/comms/atis/{id}/delete', 'CommsController@destroyATIS');
    });

    Route::group(['before' => 'roster_add'], function(){
        Route::get('/admin/roster/vatsim/{id}', 'RosterController@ajax_get_user_info');
        Route::post('/admin/roster/{id}/controller', 'AdminController@setController');
    });

    Route::group(['before' => 'roster_edit'], function(){
        Route::resource('/admin/roster', 'RosterController');
    });

    Route::group(['before' => 'roster_del'], function(){
        Route::post('/admin/roster/{id}/former', 'AdminController@setFormerController');
    });

    Route::group(['before' => 'visit'], function(){
        Route::get('/admin/visitreq', 'AdminController@showVisitRequests');
        Route::post('/admin/visitreq/{id}/accept', 'AdminController@acceptVRequest');
        Route::post('/admin/visitreq/{id}/deny', 'AdminController@denyVRequest');
        Route::post('/admin/visitreq/{id}/update', 'AdminController@updateVRequest');
    });

    Route::group(['before' => 'mentor'], function(){
        Route::resource('/admin/mentor/files', 'TrainingFilesController');
        Route::get('/admin/mentor/requests', 'MentorController@showRequests');
        Route::get('/admin/mentor/requests/{id}/edit', 'MentorController@editRequest');
        Route::post('/admin/mentor/requests/{id}/cancel', 'MentorController@cancelSession');
        Route::get('/admin/mentor/students', 'MentorController@findStudents');
        Route::post('/admin/mentor/student', 'MentorController@findStudent');
        Route::get('/admin/mentor/student/{id}', 'MentorController@student');
        Route::get('/admin/mentor/note/{id}', 'MentorController@showNote');
        Route::get('/admin/mentor/addnote', 'MentorController@addNote');
        Route::post('/admin/mentor/addnote', 'MentorController@saveNote');
        Route::get('/admin/mentor/otsrec', 'MentorController@recOTS');
        Route::post('/admin/mentor/otsrec', 'MentorController@saveOTSReq');
        Route::get('/admin/mentor/checklists', 'MentorController@showChecklists');

        Route::get('/admin/mentor/avail', 'MentorController@showAvail');
        Route::post('/admin/mentor/avail', 'MentorController@postAvail');
    });

    Route::group(['before' => 'instruct'], function(){
        Route::get('/admin/instructor/otsrec', 'InstructorController@showOTSRec');
        Route::post('/admin/instructor/otsrec/{id}/accept', 'InstructorController@acceptOTS');
        Route::post('/admin/instructor/otsrec/{id}/cancel', 'InstructorController@cancelOTS');
        Route::post('/admin/instructor/otsrec/{id}/pass', 'InstructorController@passOTS');
        Route::post('/admin/instructor/otsrec/{id}/fail', 'InstructorController@failOTS');
        Route::delete('/admin/instructor/otsrec/{id}', 'InstructorController@destroyOTS');
        Route::get('/admin/instructor/addotsnote', 'InstructorController@addOTSNote');
        Route::get('/admin/instructor/exams', 'InstructorController@showExam');
        Route::post('/admin/instructor/exams', 'InstructorController@assignExam');
        Route::delete('/admin/instructor/exams/{id}', 'InstructorController@destroyExam');
    });

    Route::group(['before' => 'feedback'], function(){
        Route::get('/admin/feedback', 'FeedbackController@showFeedback');
        Route::post('/admin/feedback/{id}/accept', 'FeedbackController@approveFeedback');
        Route::post('/admin/feedback/{id}/reject', 'FeedbackController@rejectFeedback');
        Route::get('/admin/feedback/{id}', 'FeedbackController@showFeedbackDetails');
    });

    Route::group(['before' => 'loa'], function(){
        Route::post('/admin/roster/{id}/setloa', 'AdminController@setLOA');
        Route::post('/admin/roster/{id}/setactive', 'AdminController@setActive');
    });

        
});


App::missing(function($exception){
    return Response::view('errors.missing', [], 404);
});

Route::post('/deploy', 'AdminController@deploy');

app/models/Event.php
<?php

class Event extends Eloquent {


}

app/models/Events.php
<?php

use Carbon\Carbon;

class Events extends Eloquent {
	
	public static $HostLong = [
        'VATUSA' => 'VATUSA',
        'ZAB' => 'Albuquerque ARTCC',
        'ZAN' => 'Anchorage ARTCC', 
        'ZTL' => 'Atlanta ARTCC',
        'ZBW' => 'Boston ARTCC',
        'ZAU' => 'Chicago ARTCC',
        'ZOB' => 'Cleveland ARTCC',
        'ZDV' => 'Denver ARTCC',
        'ZFW' => 'Fort Worth ARTCC',
        'HCF' => 'Honolulu CF',
        'ZHU' => 'Houston ARTCC',
        'ZID' => 'Indianapolis ARTCC',
        'ZJX' => 'Jacksonville ARTCC',
        'ZKC' => 'Kansas City ARTCC',
        'ZLA' => 'Los Angeles ARTCC',
        'ZME' => 'Memphis ARTCC',
        'ZMA' => 'Miami ARTCC',
        'ZMP' => 'Minnieapolis ARTCC',
        'ZNY' => 'New York ARTCC',
        'ZOA' => 'Oakland ARTCC',
        'ZLC' => 'Salt Lake City ARTCC',
        'ZSE' => 'Seattle ARTCC',
        'ZDC' => 'Washington DC ARTCC',
    ];

    public static $DefaultPos = [
        '1' => 'Neighbor ARTCC Support',
        '2' => 'Enroute (2-High Split)',
        '3' => 'F11 TRACON/KMCO ATCT',
        '4' => 'DAB TRACON/ATCT',
        '5' => 'JAX TRACON/ATCT',
        '6' => 'CHS TRACON/ATCT',
        '7' => 'MYR TRACON/ATCT',
        '8' => 'PNS TRACON/ATCT',
        '9' => 'SAV TRACON/ATCT'
    ];

	protected $table = 'event';

	protected $dates = ['created_at', 'updated_at', 'event_start', 'event_end'];
	protected $fillable = array('title', 'event_start', 'event_end', 'banner_link', 'description', 'host', 'status');


    public function positions() {
        return $this->hasMany('EventPosition', 'event_id');
    }

    public function getHostLongAttribute()
    {
        foreach (Events::$HostLong as $id => $long) {
            if ($this->host == $id) {
                return $long;
            }
        }

        return "";
    }

    public function getStatusLongAttribute()
    {
        switch($this->status)
        {
            case 0: return "Hidden";
            case 1: return "Active";

        }
    }

    public static function current()
    {
        return static::query()->where('status', '1')->where('event_end', '>', Carbon::now());
    }

    public function fillPositions()
    {
        //
    }
}

app/models/Visit.php
<?php

class Visit extends Eloquent {

    public static $RatingShort = [
        0 => 'N/A',
        1 => 'OBS', 2 => 'S1', 
        3 => 'S2', 4 => 'S3', 
        5 => 'C1', 7 => 'C3', 
        8 => 'I1', 10 => 'I3', 
        11 => 'SUP', 12 => 'ADM',
    ];

    protected $table = 'visit_requests';

    protected $fillable = array('cid', 'first_name', 'last_name', 'rating_id', 'email', 'home', 'accepted', 'reason');

	public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getRatingShortAttribute()
    {
        foreach (Visit::$RatingShort as $id => $Short) {
            if ($this->rating_id == $id) {
                return $Short;
            }
        }

        return "";
    }

    public function sendVReqDeclineEmail() {
        return Mail::send('emails.visitdeny', ['session' => $this], function($message){
            $message->to($this->email);
            $message->subject('ZJX - Visiting Application Denied');
        });
    }

    public function sendVReqUpdateEmail() {
        return Mail::send('emails.2weekvisitr', ['session' => $this], function($message){
            $message->to($this->email);
            $message->subject('ZJX - Visiting Application Update');
        });
    }

}

app/views/admin/events/index.blade.php
@extends('layouts.master')

@section('title')
@parent
| Events | Administrator Center
@stop

@section('content')

<!-- Hero -->
<div class="bg-gd-dusk">
	<div class="bg-black-op-25">
		<div class="content content-top content-full text-center">
			<h1 class="h3 text-white font-w700 mb-10">
			Events
			</h1>
			<h2 class="h4 font-w400 text-white-op">Jacksonville ARTCC Administrator Center</h2>
			<!-- Actions -->
			<a href="/admin/events/create" type="button" class="btn btn-hero btn-noborder btn-rounded btn-success mb-10 js-appear-enabled animated fadeInUp">
				<i class="fa fa-plus-circle mr-5"></i> Create an Event
			</a>
			<!-- END Actions -->
		</div>
	</div>
</div>
<!-- END Hero -->

<!-- Breadcrumb -->
<div class="bg-body-light border-b">
	<div class="content py-5 text-center">
		<nav class="breadcrumb bg-body-light mb-0">
			<a class="breadcrumb-item" href="/">Home</a>
			<a class="breadcrumb-item" href="/admin/dashboard">Administrator Center</a>
			<span class="breadcrumb-item active">Events</span>
		</nav>
	</div>
</div>
<!-- End Breadcrumb -->

<div class="content content-full">
	<div class="row">
		<div class="col-md-12">
			<div class="block block-themed">
				<div class="block-content">
					<div class="table-responsive">
					<table class="table table-bordered table-striped">
						<thead>
							<tr>
								<th width="25%">Event Title</th>
								<th width="25%">Event Start</th>
								<th width="25%">Event End</th>
								<th width="10%">Status</th>
								<th width="15%">Actions</th>
							</tr>
						</thead>
						<tbody>
						@forelse($event as $e)
							<tr>
								<td>{{{$e->title}}}</td>
								<td>{{{$e->event_start}}}</td>
								<td>{{{$e->event_end}}}</td>
								<td>{{{$e->status_long}}}</td>
								<td>@if($e->status == '1')
									{{Form::open(['action'=>['EventController@setEventHidden', $e->id], 'style'=>'display:inline-block'])}}
									<button type="submit" class="btn btn-warning btn-sm simple-tooltip" title="Set Hidden"><i class="fa fa-eye-slash"></i></button>
									{{Form::close()}}
									@elseif($e->status == '0')
									{{Form::open(['action'=>['EventController@setEventActive', $e->id], 'style'=>'display:inline-block'])}}
										<button type="submit" class="btn btn-success btn-sm simple-tooltip" title="Set Active"><i class="fa fa-eye"></i></button>
									{{Form::close()}}
									@endif
									{{Form::open(['action'=>['EventController@destroy', $e->id], 'method'=>'delete', 'style'=>'display:inline-block'])}}
										<button type="submit" class="btn btn-danger btn-sm simple-tooltip" title="Delete"><i class="fa fa-times"></i></button>
									{{Form::close()}}
									<a href="/admin/events/{{$e->id}}/edit" style="display:inline-block" class="btn btn-success btn-sm simple-tooltip" title="Edit"><i class="fa fa-pencil-square-o"></i></a> <a href="/admin/events/{{$e->id}}" style="display:inline-block" class="btn btn-info btn-sm simple-tooltip" title="View"><i class="fa fa-info-circle"></i></a></td>
							</tr>
						@empty
							<tr>
								<td colspan="5">No Events To Show</td>
							</tr>
						@endforelse
						</tbody>
					</table>
				</div>
				</div>
			</div>
		</div>
	</div>
</div>

@stop

app/views/admin/events/show.blade.php
@extends('layouts.master')

@section('title')
@parent
| Event Information | Administrator Center
@stop

@section('content')

@if($event) 

<!-- Hero -->
<div class="bg-gd-dusk">
	<div class="bg-black-op-25">
		<div class="content content-top content-full text-center">
			<h1 class="h3 text-white font-w700 mb-10">
				Event Information
			</h1>
			<h2 class="h4 font-w400 text-white-op">Jacksonville ARTCC Administrator Center</h2>
		</div>
	</div>
</div>
<!-- END Hero -->

<!-- Breadcrumb -->
<div class="bg-body-light border-b">
	<div class="content py-5 text-center">
		<nav class="breadcrumb bg-body-light mb-0">
			<a class="breadcrumb-item" href="/">Home</a>
			<a class="breadcrumb-item" href="/admin/dashboard">Administrator Center</a>
			<a class="breadcrumb-item" href="/admin/events">Events</a>
			<span class="breadcrumb-item active">Information</span>
		</nav>
	</div>
</div>
<!-- End Breadcrumb -->

<div class="content content-full">
	<div class="row">
		<div class="col-md-12">
			<div class="block block-themed block-rounded">
				<div class="block-header bg-primary-dark">
					<h3 class="block-title">Event Information</h3>
					<div class="block-options">
					</div>
				</div>
				<div class="block-content">
					<div class="row">
						<div class="col-sm-12">
							<div class="well">
								<h4><img width="100%" src="{{{$event->banner_link}}}"></h4>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-6">
							<div class="panel panel-primary">
								<div class="panel-heading">
									<h3 class="font-w300">Event <small>{{{$event->title}}}</small></h3>
								</div>
								<div class="panel-body">
									<h3 class="font-w300">Host <small>{{{$event->host_long}}}</small></h3>
									<h3 class="font-w300">Start <small>{{{$event->event_start}}}z</small></h3>
									<h3 class="font-w300">End <small>{{{$event->event_end}}}z</small></h3>
									<h3 class="font-w300">Event Description</h3>
									<p>{{$event->description}}</p>
								</div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="panel panel-primary">
								<div class="panel-heading">
									<h3 class="font-w300">Position Assignments</h3>
									<p>Click and drag a position to reorder it within the table.</p>
								</div>
								<div class="panel-body">
									<a class="btn btn-primary min-width-125" data-toggle="modal" data-target="#add-position">Add Position</a>
									<a class="btn btn-warning min-width-125" data-toggle="modal" data-target="#assign-position-manual">Assign Position</a><br />
									<div class="table-responsive">
										<table class="table table-striped available-positions">
											<thead>
												<tr>
													<th width="30%" style="text-align: center;">Position</th>
													<th width="50%" style="text-align: center;">Controller</th>
													<th width="20%" style="text-align: center;">Actions</th>
												</tr>
											</thead>
											<tbody>
												@foreach($event->positions->sortBy('order_index') as $position)
												<tr data-id="{{ $position->id }}">
													<td style="text-align: center;">{{$position->name}}</td>
													<td style="text-align: center;">{{$position->user ? $position->user->full_name : "No Assignment"}}</td>
													<td style="text-align: center;">
														{{ Form::open(['action' => ['EventController@deletePosition', $event->id, $position->id], 'method' => 'DELETE', 'style' => 'display: inline-block;']) }}
														<button type="submit" class="btn btn-danger btn-sm btn-addon simple-tooltip" title="Remove Position"><i class="fa fa-times"></i></button>
														{{ Form::close() }}
														@if(!$position->controller_id == null)
														{{ Form::open(['action' => ['EventController@unassignPosition', $event->id, $position->id], 'method' => 'POST', 'style' => 'display: inline-block;']) }}
														<button type="submit" class="btn btn-warning btn-sm btn-addon simple-tooltip" title="Unassign Controller"><i class="fa fa-ban"></i></button>
														{{ Form::close() }}
														@endif
													</td>
												</tr>
												@endforeach
											</tbody>
										</table>
									</div>
									<div class="panel-heading">
										<h3 class="font-w300">Position Requests</h3>
									</div>
									<div class="table-responsive">
										<table class="table table-striped">
											<thead>
												<tr>
													<th width="30%" style="text-align: center;">Position</th>
													<th width="50%" style="text-align: center;">Controller</th>
													<th width="20%" style="text-align: center;">Actions</th>
												</tr>
											</thead>
											<tbody>
												@forelse($pos_req as $p)
												<tr>
													<td style="text-align: center;">{{$p->eventPosition->name}}</td>
													<td style="text-align: center;">{{$p->user->full_name}}</td>
													<td style="text-align: center;"> {{ Form::open(['action' => ['EventController@assignPosition', $p->position_id, $p->user->id], 'method' => 'POST', 'style' => 'display: inline-block;']) }}
													<button class="btn btn-success btn-sm btn-addon simple-tooltip" title="Accept Position"><i class="fa fa-check"></i></button>{{ Form::close() }} {{ Form::open(['action' => ['EventController@deleteRequest', $p->id], 'method' => 'DELETE', 'style' => 'display: inline-block;']) }}
													<button class="btn btn-danger btn-sm btn-addon simple-tooltip" title="Delete Request"><i class="fa fa-times"></i></button>{{ Form::close() }}
													</td>
												</tr>
												@empty
												<tr>
													<td colspan="3" style="text-align: center;">No open position requests.</td>
												</tr>
												@endforelse
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="add-position" tabindex="-1" role="dialog" aria-labelledby="add-position" style="display: none;" aria-hidden="true">
	{{ Form::open(['action' => ['EventController@createPosition', $event->id], 'method' => 'POST']) }}
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="block block-themed block-transparent mb-0">
				<div class="block-header bg-primary-dark">
					<h3 class="block-title">Add Position</h3>
					<div class="block-options">
						<button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
							<i class="si si-close"></i>
						</button>
					</div>
				</div>
				<div class="block-content">
					<div class="form-group">
						<label for="position">Position Name</label>
						<input id="position" name="name" type="text" class="form-control" />
					</div>
				</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-alt-danger" data-dismiss="modal">
						<i class="fa fa-close"></i> Close
					</button>
					<button type="submit" class="btn btn-alt-success">
						<i class="fa fa-check"></i> Submit
					</button>
				</div>
		</div>
	</div>
  {{ Form::close() }}
</div>

<div class="modal fade" id="assign-position-manual" tabindex="-1" role="dialog" aria-labelledby="assign-position-manual" style="display: none;" aria-hidden="true">
	{{ Form::open(['action' => ['EventController@assignPositionManual'], 'method' => 'POST']) }}
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="block block-themed block-transparent mb-0">
				<div class="block-header bg-primary-dark">
					<h3 class="block-title">Assign Position</h3>
					<div class="block-options">
						<button type="button" class="btn-block-option" data-dismiss="modal" aria-label="Close">
							<i class="si si-close"></i>
						</button>
					</div>
				</div>
				<div class="block-content">
					<div class="form-group">
						<label for="position_id">Position</label>
						<select name="position_id" id="position_id" class="form-control">
						@foreach($event->positions->sortBy('order_index') as $position)
						<option value="{{ $position->id }}">{{$position->name}}</option>
						@endforeach
						</select>
					</div>
					<div class="form-group">
						<label for="controller_id">Controller Name</label>
						<select name="controller_id" id="controller_id" class="form-control">
						@foreach($controllers as $c)
							<option value="{{{$c->id}}}">{{{$c->backwards_name}}}</option>
						@endforeach
						</select>
						<!--<input id="controller_id" name="controller_id" type="text" class="form-control" />-->
					</div>
				</div>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-alt-danger" data-dismiss="modal">
						<i class="fa fa-close"></i> Close
					</button>
					<button type="submit" class="btn btn-alt-success">
						<i class="fa fa-check"></i> Submit
					</button>
				</div>
		</div>
	</div>
  {{ Form::close() }}
</div>

<script>
var fixHelper = function(e, ui) {
	ui.children().each(function() {
		$(this).width($(this).width());
	});
	return ui;
};

$(".available-positions tbody").sortable({
	helper: fixHelper
}).disableSelection();

$(".available-positions tbody").on('sortstop', function(e, ui){
	var new_order = [];

	$(".available-positions tbody tr").each(function(i, row){
		new_order.push({
			id: $(row).data('id'),
			order_index: i
		});
	});

	$.post('/admin/events/{{ $event->id }}/sort_positions', JSON.stringify(new_order), function(r){
		console.log("Successfully resorted the positions");
	}, 'json');
})
</script>

@else
<!-- Page Content -->
<div class="content content-full">
	<div class="hero-inner">
		<div class="content content-full">
			<div class="py-30 text-center">
				<div class="display-3 text-danger">
					<i class="fa fa-warning"></i> Event Error
				</div>
				<h1 class="h2 font-w700 mt-30 mb-10">You just found an error page!</h1>
				<h2 class="h3 font-w400 text-muted mb-50">We are sorry. The event you are looking for was not found.</h2>
				<a class="btn btn-hero btn-rounded btn-alt-secondary" href="/admin/events">
					<i class="fa fa-arrow-left mr-10"></i> Back to Events
				</a>
			</div>
		</div>
	</div>
</div>
<!-- END Page Content -->
@endif


@stop