app/models/Event.php
<?php

class Event extends Eloquent {


}

app/models/Events.php
<?php

use Carbon\Carbon;

class Events extends Eloquent {
	
	public static $HostLong = [
        'VATUSA' => 'VATUSA',
        'ZAB' => 'Albuquerque ARTCC',
        'ZAN' => 'Anchorage ARTCC', 
        'ZTL' => 'Atlanta ARTCC',
        'ZBW' => 'Boston ARTCC',
        'ZAU' => 'Chicago ARTCC',
        'ZOB' => 'Cleveland ARTCC',
        'ZDV' => 'Denver ARTCC',
        'ZFW' => 'Fort Worth ARTCC',
        'HCF' => 'Honolulu CF',
        'ZHU' => 'Houston ARTCC',
        'ZID' => 'Indianapolis ARTCC',
        'ZJX' => 'Jacksonville ARTCC',
        'ZKC' => 'Kansas City ARTCC',
        'ZLA' => 'Los Angeles ARTCC',
        'ZME' => 'Memphis ARTCC',
        'ZMA' => 'Miami ARTCC',
        'ZMP' => 'Minnieapolis ARTCC',
        'ZNY' => 'New York ARTCC',
        'ZOA' => 'Oakland ARTCC',
        'ZLC' => 'Salt Lake City ARTCC',
        'ZSE' => 'Seattle ARTCC',
        'ZDC' => 'Washington DC ARTCC',
    ];

    public static $DefaultPos = [
        '1' => 'Neighbor ARTCC Support',
        '2' => 'Enroute (2-High Split)',
        '3' => 'F11 TRACON/KMCO ATCT',
        '4' => 'DAB TRACON/ATCT',
        '5' => 'JAX TRACON/ATCT',
        '6' => 'CHS TRACON/ATCT',
        '7' => 'MYR TRACON/ATCT',
        '8' => 'PNS TRACON/ATCT',
        '9' => 'SAV TRACON/ATCT'
    ];

	protected $table = 'event';

	protected $dates = ['created_at', 'updated_at', 'event_start', 'event_end'];
	protected $fillable = array('title', 'event_start', 'event_end', 'banner_link', 'description', 'host', 'status');


    public function positions() {
        return $this->hasMany('EventPosition', 'event_id');
    }

    public function getHostLongAttribute()
    {
        foreach (Events::$HostLong as $id => $long) {
            if ($this->host == $id) {
                return $long;
            }
        }

        return "";
    }

    public function getStatusLongAttribute()
    {
        switch($this->status)
        {
            case 0: return "Hidden";
            case 1: return "Active";

        }
    }

    public static function current()
    {
        return static::query()->where('status', '1')->where('event_end', '>', Carbon::now());
    }

    public function fillPositions()
    {
        //
    }
}

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Zizaco\Entrust\HasRole;


class User extends Eloquent implements UserInterface {
    use UserTrait;
    use HasRole;

    public static $RatingShort = [
        0 => 'N/A',
        1 => 'OBS', 2 => 'S1', 
        3 => 'S2', 4 => 'S3', 
        5 => 'C1', 7 => 'C3', 
        8 => 'I1', 10 => 'I3', 
        11 => 'SUP', 12 => 'ADM',
    ];

    public $timestamps = true;

    public static $RatingLong = [
        0 => 'Pilot',
        1 => 'Pilot/Observer', 2 => 'Student 1', 
        3 => 'Student 2', 4 => 'Student 3', 
        5 => 'Controller 1', 7 => 'Controller 3', 
        8 => 'Instructor 1', 10 => 'Instructor 3', 
        11 => 'Supervisor', 12 => 'Administrator',
    ];

    public static $StaffRoleToSMFGroup = [
        '0' => '20',
        '1' => '9',
        '2' => '10',
        '3' => '11',
        '4' => '12',
        '5' => '13',
        '6' => '14',
        '7' => '15',
        '8' => '16',
        '9' => '17',
        '12' => '9',
        '13'=> '22',
    ];

    public static $TrainingRoleToSMFGroup = [
        '0' => '',
        '10' => '18',
        '11' => '19',
    ];

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'roster';

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = array('password', 'remember_token');

    protected $fillable = array('id', 'first_name', 'last_name', 'email', 'rating_id', 'canTrain', 'visitor', 'visitor_from', 'status', 'loa', 'del', 'gnd', 'twr', 'app', 'ctr');

    public function controller_log() {
        $this->hasMany('ControllerLog', 'cid');
    }

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getBackwardsNameAttribute()
    {
        return $this->last_name . ", " . $this->first_name;
    }

    public function getRatingShortAttribute()
    {
        foreach (User::$RatingShort as $id => $Short) {
            if ($this->rating_id == $id) {
                return $Short;
            }
        }

        return "";
    }

    public function getRatingLongAttribute()
    {
        foreach (User::$RatingLong as $id => $Long) {
            if ($this->rating_id == $id) {
                return $Long;
            }
        }

        return "";
    }

    public function getLocalHoursAttribute()
    {
        $duration = DB::table('controller_log')->where('cid', $this->id)
            ->where(function($query){
                $query->where('position', 'LIKE', '%_DEL')
                      ->orWhere('position', 'LIKE', '%_GND')
                      ->orWhere('position', 'LIKE', '%_TWR');
            })
            ->whereRaw("date_format(STR_TO_DATE(`date`, '%m/%d/%Y'), '%m/%Y') = date_format(now(), '%m/%Y')")
            ->sum('duration'); 

        if(!$duration == 0) {
            $hours = $duration / 3600;
            return number_format($hours, 2);
        } else {
            return '--';
        }
    }

    public function getApproachHoursAttribute()
    {
        $duration = DB::table('controller_log')
            ->where('cid', $this->id)
            ->where('position', 'LIKE', '%_APP')
            ->whereRaw("date_format(STR_TO_DATE(`date`, '%m/%d/%Y'), '%m/%Y') = date_format(now(), '%m/%Y')")
            ->sum('duration');

        if(!$duration == 0) {
            $hours = $duration / 3600;
            return number_format($hours, 2);
        } else {
            return '--';
        }
    }

    public function getCenterHoursAttribute()
    {
        $duration = DB::table('controller_log')
            ->where('cid', $this->id)
            ->where('position', 'LIKE', '%_CTR')
            ->whereRaw("date_format(STR_TO_DATE(`date`, '%m/%d/%Y'), '%m/%Y') = date_format(now(), '%m/%Y')")
            ->sum('duration');

        if(!$duration == 0) {
            $hours = $duration / 3600;
            return number_format($hours, 2);
        } else {
            return '--';
        }
    }

    public function getTotalHoursAttribute()
    {
        $duration = DB::table('controller_log')
            ->where('cid', $this->id)
            ->whereRaw("date_format(STR_TO_DATE(`date`, '%m/%d/%Y'), '%m/%Y') = date_format(now(), '%m/%Y')")
            ->sum('duration');
        
        if(!$duration == 0) {
            $hours = $duration / 3600;
            return number_format($hours, 2);
        } else {
            return '--';
        }
    }

    public function getStaffLongAttribute()
    {
        switch($this->staff_role)
        {
            case 'ATM': return "Air Traffic Manager";
            case 'DATM': return "Deputy Air Traffic Manager";
            case 'TA': return "Training Administrator";
            case 'WM': return "Webmaster";
            case 'FE': return "Facility Engineer";
            case 'EC': return "Events Coordinator";
            case 'ATA': return "Assistant Training Administrator";
            case 'AEC': return "Assistant Events Coordinator";
            case 'AWM': return "Assistant Webmaster";

        }
    }

    public function getDelCertAttribute()
    {
        switch($this->del)
        {
            case 0: return "No Certification";
            case 1: return "Minor Training";
            case 2: return "Minor Certified";
            case 3: return "Major Training";
            case 4: return "Major Certified";

        }
    }

    public function getGndCertAttribute()
    {
        switch($this->gnd)
        {
            case 0: return "No Certification";
            case 1: return "Minor Training";
            case 2: return "Minor Certified";
            case 3: return "Major Training";
            case 4: return "Major Certified";

        }
    }

    public function getTwrCertAttribute()
    {
        switch($this->twr)
        {
            case 0: return "No Certification";
            case 1: return "Minor Training";
            case 2: return "Minor Certified";
            case 3: return "Major Training";
            case 4: return "Major Certified";

        }
    }

    public function getAppCertAttribute()
    {
        switch($this->app)
        {
            case 0: return "No Certification";
            case 1: return "Minor Training";
            case 2: return "Minor Certified";
            case 3: return "Major Training";
            case 4: return "Major Certified";

        }
    }

    public function getCtrCertAttribute()
    {
        switch($this->ctr)
        {
            case 0: return "No Certification";
            case 1: return "Training";
            case 2: return "Certified";

        }
    }

    public function createSMFMember()
    {
        require_once(Config::get('services.smf.path') . "/smf_2_api.php");

        $registration_options = [
            'member_name' => $this->id,
            'email' => $this->email,
            'real_name' => $this->full_name,
            'password' => uniqid(),
            'require' => 'nothing', // No known password is required
            'id_group' => $this->visitor === 1 ? '20' : '19',
        ];

        $result = smfapi_registerMember($registration_options);

        if (is_array($result))
            throw new \Exception("Error attempting to register smf member: " . var_export($result, true));
    }

    /*
     * CAUTION:
     * Only call this method when the user has been properly authenticated.
     * This will log them into an smf session regardless of currently laravel session.
     */
    public function loginToSMF()
    {
        require_once(Config::get('services.smf.path') . "/smf_2_api.php");

        smfapi_login($this->id);

        setcookie("ids_loggedin", $this->id, 0, "", ".zjxartcc.org");
        $_SESSION['loggedin'] = $this->id;
    }

    /*
     * Only call this method when the user has been properly authenticated.
     * This will log them into an smf session regardless of currently laravel session.
     */
    public function logoutOfSMF()
    {
        require_once(Config::get('services.smf.path') . "/smf_2_api.php");

        // We don't care if the logout failed
        smfapi_logout($this->id);
    }

    public function sendVReqDeclineEmail() {
        return Mail::send('emails.visitdeny', ['session' => $this], function($message){
            $message->to($this->visitr->email);
            $message->subject('ZJX - Visiting Application Denied');
        });
    }

    public function sendVReqUpdateEmail() {
        return Mail::send('emails.2weekvisitr', ['session' => $this], function($message){
            $message->to($this->visitr->email);
            $message->subject('ZJX - Visiting Application Update');
        });
    }

    public function hasStaff()
    {
        if($this->hasRole('ATM') || $this->hasRole('DATM') || $this->hasRole('TA') || $this->hasRole('WM') || $this->hasRole('ATA') || $this->hasRole('AEC') || $this->hasRole('EC') || $this->hasRole('FE') || $this->hasRole('AWM')) {
            return true;
        } else {
            return false;
        }
    }

    public function hasTrainingStaff()
    {
        if($this->hasRole('INS') || $this->hasRole('MTR')) {
            return true;
        } else {
            return false;
        }
    }

    public function userFirstStaff()
    {
        $assignedrole = DB::table(Config::get('entrust::assigned_roles_table'))->where('user_id', $this->id)->first();
        $role = DB::table(Config::get('entrust::roles_table'))->where('id', $assignedrole->role_id)->first();
        return $role->name;
    }

    public function siteActivity()
    {
    	return $this->hasMany('ActivityLog', 'user_id', 'id')->orderBy('id', 'DESC')->first();
    }

    public function controlActivity()
    {
    	return $this->hasMany('ControllerLog', 'cid', 'id')->orderBy('id', 'DESC')->first();
    }
    
    public function quarterlyHours($quarter,$year)
    {

app/views/admin/events/create.blade.old.php
@extends('layouts.master')

@section('title')
@parent
| Events
@stop

@section('content')

<div class="page-heading-two">
    <div class="container">
        <h2>Events - Admin - Create</h2>
    </div>
</div>
    
    <div class="container">
       {{ Form::open(['action' => 'EventController@store']) }}
       		<div class="row">
       			<div class="col-sm-12">
		       		<div class="form-group">
		       			{{Form::label('title', 'Event Title:', ['class'=>'control-label'])}}
		                {{Form::text('title', null, ['class'=>'form-control'])}}
		       		</div>
		       	</div>
		    </div>
		    <div class="row">
		    	<div class="col-sm-12">
		       		<div class="form-group">
		       			{{Form::label('description', 'Event Description:', ['class'=>'control-label'])}}
		                {{Form::hidden('description', null)}}
		                @include('partials.quill', ['id' => 'description'])
		       		</div>
		       	</div>
	       	</div>
       		<div class="row">
	       		<div class="col-sm-6">
		       		<div class="form-group">
		       			{{Form::label('start', 'Event Start Time:', ['class'=>'control-label'])}}
		       			<div class="input-group date" id="start-date">
		       				{{Form::text('event_start', null, ['class'=>'form-control'])}}
		       				<span class="input-group-addon">
		       					<i class="fa fa-calendar"></i>
		       				</span>
		       			</div>
		       		</div>
		       	</div>
		       	<div class="col-sm-6">
		       		<div class="form-group">
		       			{{Form::label('end', 'Event End Time:', ['class'=>'control-label'])}}
		       			<div class="input-group date" id="end-date">
		       				{{Form::text('event_end', null, ['class'=>'form-control'])}}
		       				<span class="input-group-addon">
		       					<i class="fa fa-calendar"></i>
		       				</span>
		       			</div>
		       		</div>
	       		</div>
	       	</div>
	       	<div class="row">
		       	<div class="col-sm-4">
			       	<div class="form-group">
			       	    <div class="col-sm-12" style="padding-left:0px;">
		       			{{Form::label('banner_link', 'Banner Link:', ['class'=>'control-label'])}}
		       			</div>
		       			<div class="col-sm-8" style="padding-left:0px; padding-right:0px;">
		                    {{Form::text('banner_link', null, ['class'=>'form-control'])}}
		                </div>
		                <!--<a class="btn btn-success btn-sm col-sm-4" data-toggle="modal" data-target="#upload-banner">Upload Banner</a>-->
		       		</div>
		       	</div>
		       	<div class="col-sm-4">
		       		<div class="form-group">
		                {{Form::label('host', 'Host ARTCC/Facility:', ['class'=>'control-label'])}}
		                {{Form::select('host', Events::$HostLong, 'ZJX', ['class' => 'form-control'])}}
		            </div>
		        </div>
		        <div class="col-sm-4">
		        	<div class="form-group">
		                {{Form::label('defaultpos', 'Default Positions:', ['class'=>'control-label'])}}
		                {{Form::select('defaultpos', Events::$DefaultPos, 'null', ['class' => 'form-control'])}}
		            </div>
		        </div>
	        </div>

	        <div class="row">
		        <div class="col-sm-12">
		       		<div class="form-group">
		       			{{Form::submit('Submit', ['class' => 'btn btn-primary btn-block'])}}
		       		</div>
	       		</div>
	       	</div>

       {{ Form::close() }}

       <script>
            $(function () {
            	var dtpOptions = {
                	icons: {
	                    time: "fa fa-clock-o",
	                    date: "fa fa-calendar",
	                    up: "fa fa-arrow-up",
	                    down: "fa fa-arrow-down"
	                },
	                format: 'MM/DD/YYYY H:mm'
                };

                $('#start-date').datetimepicker(dtpOptions);
                $('#end-date').datetimepicker(dtpOptions);
            });
       </script>
    </div>
    
    



@stop

app/views/admin/events/edit.blade.old.php
@extends('layouts.master')

@section('title')
@parent
| Events
@stop

@section('content')

<div class="page-heading-two">
		<div class="container">
				<h2>Events - Admin - Edit</h2>
		</div>
</div>
		
<div class="container">
	 {{ Form::open(['action' => ['EventController@update', $event->id], 'method' => 'PUT']) }}
			<div class="col-sm-12">
				<div class="form-group">
					{{Form::label('title', 'Event Title:', ['class'=>'control-label'])}}
					{{Form::text('title', $event->title, ['class'=>'form-control'])}}
				</div>
				<div class="form-group">
					{{Form::label('description', 'Event Description:', ['class'=>'control-label'])}}
					{{Form::hidden('description', $event->description)}}
					@include('partials.quill', ['id' => 'description'])
				</div>
			</div>
			<div class="col-sm-6">
				<div class="form-group">
					{{Form::label('event_start', 'Event Start Time:', ['class'=>'control-label'])}}
					<div class="input-group date" id="start-date">
						{{Form::text('event_start', $event->event_start->format('m/d/Y H:i'), ['class'=>'form-control'])}}
						<span class="input-group-addon">
							<i class="fa fa-calendar"></i>
						</span>
					</div>
				</div>
			</div>
			<div class="col-sm-6">
				<div class="form-group">
					{{Form::label('event_end', 'Event End Time:', ['class'=>'control-label'])}}
					<div class="input-group date" id="end-date">
						{{Form::text('event_end', $event->event_end->format('m/d/Y H:i'), ['class'=>'form-control'])}}
						<span class="input-group-addon">
							<i class="fa fa-calendar"></i>
						</span>
					</div>
				</div>
			</div>
			<div class="col-sm-12">
				<div class="form-group">
					{{Form::label('banner_link', 'Banner Link:', ['class'=>'control-label'])}}
					{{Form::text('banner_link', $event->banner_link, ['class'=>'form-control'])}}
				</div>
				<div class="form-group">
					{{Form::label('host', 'Host ARTCC/Facility:', ['class'=>'control-label'])}}
					{{Form::select('host', Events::$HostLong, $event->host, ['class' => 'form-control'])}}
				</div>
			</div>

			<div class="col-sm-12">
				<div class="form-group">
					{{Form::submit('Submit', ['class' => 'btn btn-primary'])}}
				</div>
			</div>

	 {{ Form::close() }}

	<script>
		$(function () {
			var dtpOptions = {
					icons: {
							time: "fa fa-clock-o",
							date: "fa fa-calendar",
							up: "fa fa-arrow-up",
							down: "fa fa-arrow-down"
					},
					format: 'MM/DD/YYYY H:mm'
				};

				$('#start-date').datetimepicker(dtpOptions);
				$('#end-date').datetimepicker(dtpOptions);

				$('#start-date').on('dp.change', function(e) {
					$("#end-date").data('DateTimePicker').minDate(e.date);
				});

				$('#end-date').on('dp.change', function(e) {
					$("#start-date").data('DateTimePicker').maxDate(e.date);
				});

		});
	 </script>

</div>

@stop

app/views/admin/events/show.blade.old.php
@extends('layouts.master')

@section('title')
@parent
| Event
@stop

@section('content')

<div class="page-heading-two">
	<div class="container">
		<h2>Event - Admin - View</h2>
	</div>
</div>

@if($event)    
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<div class="well">
				<h4><img width="100%" src="{{{$event->banner_link}}}"></h4>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-6">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">{{{$event->title}}}</h3>
				</div>
				<div class="panel-body">
					<h4 style="display:inline-block;">Host ARTCC:</h4> <h4 style="display:inline-block;">{{{$event->host_long}}}</h4><br />
					<h4 style="display:inline-block;">Event Date:</h4> <h4 style="display:inline-block;">{{{$event->event_start}}}z - {{{$event->event_end}}}z</h4>
					<h4><strong>Event Description</strong></h4>
					<p>{{$event->description}}</p>
				</div>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h3 class="panel-title">Event Positions</h3>
				</div>
				<div class="panel-body">
					<div class="table-responsive">
						<table class="table table-striped available-positions">
							<thead>
								<tr>
									<th width="20%">Position</th>
									<th width="60%">Controller</th>
									<th width="20%">Actions</th>
								</tr>
							</thead>
							<tbody>
								@foreach($event->positions->sortBy('order_index') as $position)
								<tr data-id="{{ $position->id }}">
									<td>{{$position->name}}</td>
									<td>{{$position->user ? $position->user->full_name : "No Assignment"}}</td>
									<td>
										{{ Form::open(['action' => ['EventController@deletePosition', $event->id, $position->id], 'method' => 'DELETE', 'style' => 'display: inline-block;']) }}
										<button type="submit" class="btn btn-danger btn-sm btn-addon simple-tooltip" title="Remove Position"><i class="fa fa-times"></i></button>
										{{ Form::close() }}
										@if(!$position->controller_id == null)
										{{ Form::open(['action' => ['EventController@unassignPosition', $event->id, $position->id], 'method' => 'POST', 'style' => 'display: inline-block;']) }}
										<button type="submit" class="btn btn-warning btn-sm btn-addon simple-tooltip" title="Unassign Controller"><i class="fa fa-ban"></i></button>
										{{ Form::close() }}
										@endif
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>
					<a class="btn btn-success btn-sm" data-toggle="modal" data-target="#add-position">Add Position</a>
					<a class="btn btn-warning btn-sm" data-toggle="modal" data-target="#assign-position-manual">Assign Position</a><br />
					<div class="table-responsive">
						<table class="table table-striped">
							<thead>
								<tr>
									<th width="50%">Controller</th>
									<th width="30">Position</th>
									<th width="20%">Actions</th>
								</tr>
							</thead>
							<tbody>
								@forelse($pos_req as $p)
								<tr>
									<td>{{$p->user->full_name}}</td>
									<td>{{$p->eventPosition->name}}</td>
									<td> {{ Form::open(['action' => ['EventController@assignPosition', $p->position_id, $p->user->id], 'method' => 'POST', 'style' => 'display: inline-block;']) }}
									<button class="btn btn-success btn-sm btn-addon simple-tooltip" title="Accept Position"><i class="fa fa-check"></i></button>{{ Form::close() }} {{ Form::open(['action' => ['EventController@deleteRequest', $p->id], 'method' => 'DELETE', 'style' => 'display: inline-block;']) }}
									<button class="btn btn-danger btn-sm btn-addon simple-tooltip" title="Delete Request"><i class="fa fa-times"></i></button>{{ Form::close() }}
									</td>
								</tr>
								@empty
								<tr>
									<td colspan="3">No Position Requests</td>
								</tr>
								@endforelse
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="add-position">
	{{ Form::open(['action' => ['EventController@createPosition', $event->id], 'method' => 'POST']) }}
	  <div class="modal-dialog">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title">Add Position</h4>
		  </div>
		  <div class="modal-body">
			
			<div class="form-group">
				<label for="position">Position</label>
				<input id="position" name="name" type="text" class="form-control" />
			</div>
			
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			<button type="submit" class="btn btn-primary">Create</button>
		  </div>
		</div>
	  </div>
  {{ Form::close() }}
</div>

<div class="modal fade" id="assign-position-manual">
	{{ Form::open(['action' => ['EventController@assignPositionManual'], 'method' => 'POST']) }}
	  <div class="modal-dialog">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title">Assign Position</h4>
		  </div>
		  <div class="modal-body">
			
			<div class="form-group">
				<label for="position_id">Position</label>
				<select name="position_id" id="position_id" class="form-control">
				@foreach($event->positions->sortBy('order_index') as $position)
                <option value="{{ $position->id }}">{{$position->name}}</option>
                @endforeach
                </select>
			</div>
			<div class="form-group">
				<label for="controller_id">Controller Name</label>
				<select name="controller_id" id="controller_id" class="form-control">
			    @foreach($controllers as $c)
			        <option value="{{{$c->id}}}">{{{$c->backwards_name}}}</option>
			    @endforeach
                </select>
				<!--<input id="controller_id" name="controller_id" type="text" class="form-control" />-->
			</div>
			
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			<button type="submit" class="btn btn-primary">Assign</button>
		  </div>
		</div>
	  </div>
  {{ Form::close() }}
</div>

<script>
var fixHelper = function(e, ui) {
	ui.children().each(function() {
		$(this).width($(this).width());
	});
	return ui;
};

$(".available-positions tbody").sortable({
	helper: fixHelper
}).disableSelection();

$(".available-positions tbody").on('sortstop', function(e, ui){
	var new_order = [];

	$(".available-positions tbody tr").each(function(i, row){
		new_order.push({
			id: $(row).data('id'),
			order_index: i
		});
	});

	$.post('/admin/events/{{ $event->id }}/sort_positions', JSON.stringify(new_order), function(r){
		console.log("Successfully resorted the positions");
	}, 'json');
})
</script>

@else
<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h3>NO EVENT FOUND</h3>
			</div>
		</div>
	</div>
@endif


@stop