app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', 'FrontController@showWelcome');
Route::get('/admin/dashboard', 'AdminController@index');
Route::get('/index-tables', 'FrontController@loadHomeTables');
Route::get('/roster', 'RosterController@front_index');
Route::get('/staff', 'FrontController@showStaff');
Route::get('/weather', 'FrontController@showWeather');
Route::get('/documents', 'FrontController@showDocuments');
Route::get('/scenery', 'FrontController@showScenery');
Route::get('/stats/{year?}/{month?}', 'FrontController@showStats');
Route::get('/event/{id}', 'FrontController@showEvents');
Route::resource('/feedback', 'FeedbackController');
Route::get('/login', 'RosterController@loginv2');
Route::get('/test-login/{cid}', 'RosterController@testLogin');
// Route::get('/login2', 'RosterController@loginv2');
Route::get('/visit', 'FrontController@showVisit');
Route::post('/visit', 'AdminController@saveVisit');
Route::get('/test', 'FrontController@showTest');
Route::get('/comms', 'FrontController@showComms');
Route::get('/log', 'AdminController@showUserLog');
Route::get('/log/{id}', 'AdminController@log');
Route::get('/privacy', 'FrontController@showPrivacy');


Route::get('/sendemail', 'FrontController@sendEmail');
Route::get('/airports', 'FrontController@showAirportList');
Route::get('/airports/{id}', 'FrontController@getAirport');
Route::get('/runways', 'FrontController@showRunways');

Route::get('/admin/announcements', 'AdminController@showAnnouncements');
Route::post('/admin/announcements/{id}/update', 'AdminController@updateAnnouncements');

Route::get('/trainingcenter', 'TrainingCenter@showIndex');
Route::get('/trainingcenter/{view}', 'TrainingCenter@showTraining')->where('view', '.*');

Route::group(['before' => 'auth'], function(){
    Route::get('/ids', 'IDSController@showIDS');

    Route::get('/admin/email-password', 'EmailController@index');
    Route::post('/admin/email-password', 'EmailController@setPassword');

    //user routes
    Route::get('/logout', 'RosterController@logout');
    Route::get('/profile/{id?}', 'FrontController@showProfile');
    Route::get('/atcast', 'FrontController@showATCast');
    Route::post('/event/{id}/request', 'EventController@requestPosition');
    Route::post('/event/{id}/unassign', 'EventController@selfUnnasign');
    Route::post('/event/{id}/assignPositionManual', 'EventController@assignPositionManual');
    //Route::post('/event/uploadBanner','EventController@uploadBanner');
    Route::get('/admin/announcements', 'AdminController@showAnnouncements');
    Route::post('/admin/announcements/{id}/update', 'AdminController@updateAnnouncements');

/*
    Route::post('/admin/broadcast/create', 'BroadcastController@store');
    Route::resource('/admin/broadcast', 'BroadcastController');
*/
    Route::get('/admin/activitylog', 'AdminController@showActivityLog');
    Route::get('/admin/activitylog/filter/{id}', 'AdminController@filterActivityLog');
    
    //training routes
    Route::get('/training', 'TrainingController@showRequests');
    Route::delete('/training/{id}/delete', 'TrainingController@cancelSession');
    Route::get('/training/exams', 'TrainingController@showExams');
    Route::get('/training/notes', 'TrainingController@showNotes');
    Route::get('/training/note/{id}', 'TrainingController@showNote');
    Route::get('training/pexams', 'ExamController@showPendingPracticalExams');
    Route::get('/training/pexams/history', 'ExamController@showCompletedPracticalExams');
    Route::get('/training/texams', 'ExamController@showPendingTheoryExams');
    Route::get('/training/texams/history', 'ExamController@showCompletedTheoryExams');
    Route::get('/training/mentoravail', 'TrainingController@showMentAvail');
    Route::post('/training/mentoravail', 'TrainingController@saveSession');

    Route::group(['before' => 'events'], function(){
        Route::resource('/admin/events', 'EventController');
        Route::post('/admin/events/{id}/sort_positions', 'EventController@resortPositions');
        Route::post('/admin/events/{id}/position', 'EventController@createPosition');
        Route::delete('/admin/events/{event_id}/position/{position_id}', 'EventController@deletePosition');
        Route::post('/admin/events/{event_id}/position/{position_id}/unassign', 'EventController@unassignPosition');
        Route::post('/admin/events/position/{position_id}/assign/{controller_id}', 'EventController@assignPosition');
        Route::delete('/admin/events/posreq/{id}/delete', 'EventController@deleteRequest');
        Route::post('/admin/events/{id}/active', 'EventController@setEventActive');
        Route::post('/admin/events/{id}/hidden', 'EventController@setEventHidden');
    });

    Route::group(['before' => 'docs'], function(){
        Route::resource('/admin/docs', 'DocumentController', ['except' => ['show']]);
    });

    Route::group(['before' => 'snrstaff'], function(){
        Route::get('/admin/mentorhist', 'AdminController@showMentorHistory');
        Route::get('/api/roster', 'ApiController@roster');
        Route::get('/admin/rostertidy', 'AdminController@showRosterCleanup');
        Route::post('/admin/rostertidy/{id}/sendwarning', 'AdminController@sendWarning');
    });

    Route::group(['before' => 'scenery'], function(){
        Route::resource('/admin/scenery', 'SceneryController');
        Route::resource('/admin/comms', 'CommsController', ['except' => ['show']]);
        Route::get('/admin/comms/atis', 'CommsController@ATISindex');
        Route::post('/admin/comms/atis/{id}/store', 'CommsController@storeATIS');
        Route::post('/admin/comms/atis/{id}/update', 'CommsController@updateATIS');
        Route::delete('/admin/comms/atis/{id}/delete', 'CommsController@destroyATIS');
    });

    Route::group(['before' => 'roster_add'], function(){
        Route::get('/admin/roster/vatsim/{id}', 'RosterController@ajax_get_user_info');
        Route::post('/admin/roster/{id}/controller', 'AdminController@setController');
    });

    Route::group(['before' => 'roster_edit'], function(){
        Route::resource('/admin/roster', 'RosterController');
    });

    Route::group(['before' => 'roster_del'], function(){
        Route::post('/admin/roster/{id}/former', 'AdminController@setFormerController');
    });

    Route::group(['before' => 'visit'], function(){
        Route::get('/admin/visitreq', 'AdminController@showVisitRequests');
        Route::post('/admin/visitreq/{id}/accept', 'AdminController@acceptVRequest');
        Route::post('/admin/visitreq/{id}/deny', 'AdminController@denyVRequest');
        Route::post('/admin/visitreq/{id}/update', 'AdminController@updateVRequest');
    });

    Route::group(['before' => 'mentor'], function(){
        Route::resource('/admin/mentor/files', 'TrainingFilesController');
        Route::get('/admin/mentor/requests', 'MentorController@showRequests');
        Route::get('/admin/mentor/requests/{id}/edit', 'MentorController@editRequest');
        Route::post('/admin/mentor/requests/{id}/cancel', 'MentorController@cancelSession');
        Route::get('/admin/mentor/students', 'MentorController@findStudents');
        Route::post('/admin/mentor/student', 'MentorController@findStudent');
        Route::get('/admin/mentor/student/{id}', 'MentorController@student');
        Route::get('/admin/mentor/note/{id}', 'MentorController@showNote');
        Route::get('/admin/mentor/addnote', 'MentorController@addNote');
        Route::post('/admin/mentor/addnote', 'MentorController@saveNote');
        Route::get('/admin/mentor/otsrec', 'MentorController@recOTS');
        Route::post('/admin/mentor/otsrec', 'MentorController@saveOTSReq');
        Route::get('/admin/mentor/checklists', 'MentorController@showChecklists');

        Route::get('/admin/mentor/avail', 'MentorController@showAvail');
        Route::post('/admin/mentor/avail', 'MentorController@postAvail');
    });

    Route::group(['before' => 'instruct'], function(){
        Route::get('/admin/instructor/otsrec', 'InstructorController@showOTSRec');
        Route::post('/admin/instructor/otsrec/{id}/accept', 'InstructorController@acceptOTS');
        Route::post('/admin/instructor/otsrec/{id}/cancel', 'InstructorController@cancelOTS');
        Route::post('/admin/instructor/otsrec/{id}/pass', 'InstructorController@passOTS');
        Route::post('/admin/instructor/otsrec/{id}/fail', 'InstructorController@failOTS');
        Route::delete('/admin/instructor/otsrec/{id}', 'InstructorController@destroyOTS');
        Route::get('/admin/instructor/addotsnote', 'InstructorController@addOTSNote');
        Route::get('/admin/instructor/exams', 'InstructorController@showExam');
        Route::post('/admin/instructor/exams', 'InstructorController@assignExam');
        Route::delete('/admin/instructor/exams/{id}', 'InstructorController@destroyExam');
    });

    Route::group(['before' => 'feedback'], function(){
        Route::get('/admin/feedback', 'FeedbackController@showFeedback');
        Route::post('/admin/feedback/{id}/accept', 'FeedbackController@approveFeedback');
        Route::post('/admin/feedback/{id}/reject', 'FeedbackController@rejectFeedback');
        Route::get('/admin/feedback/{id}', 'FeedbackController@showFeedbackDetails');
    });

    Route::group(['before' => 'loa'], function(){
        Route::post('/admin/roster/{id}/setloa', 'AdminController@setLOA');
        Route::post('/admin/roster/{id}/setactive', 'AdminController@setActive');
    });

        
});


App::missing(function($exception){
    return Response::view('errors.missing', [], 404);
});

Route::post('/deploy', 'AdminController@deploy');

app/models/Feedback.php
<?php



class Feedback extends Eloquent {



    public static $Positions = [

     'JAX_CTR' => 'Enroute (Jacksonville Center)',

     'APP' => 'TRACON (Approach/Departure)',
		
     'TWR' => 'Tower',
		
     'GND' => 'Ground',
		
     'DEL' => 'Delivery',

     'UNKNOWN' => 'Unknown'

    ];



    protected $table = 'feedback';



    protected $fillable = array('controller_id', 'position', 'level', 'comments', 'staff_comments', 'pilot_name', 'pilot_id', 'pilot_email', 'flight_callsign', 'status');



    public function controller() {

        return $this->hasOne('User', 'id', 'controller_id');

    }



    public function getLevelTextAttribute()

    {

    	switch($this->level)

    	{

    		case 0: return "Unsatisfactory";

    		case 1: return "Poor";

    		case 2: return "Fair";

    		case 3: return "Good";

    		case 4: return "Excellent";

    	}

    }



    public function getFeedbackPosAttribute()

    {

        foreach (Feedback::$Positions as $id => $Long) {

            if ($this->position == $id) {

                return $Long;

            }

        }



        return "";

    }



    public function sendPilotEmail()

    {

        return Mail::send('emails.feedbackpilot', ['feedback' => $this], function($message){

            $message->from('no-reply@zjxartcc.org', 'ZJX No-Reply');

            $message->to($this->pilot_email);

            $message->subject('ZJX - Feedback Response');

        });

    }



    public function sendControllerEmail()

    {

        return Mail::send('emails.feedbackcontroller', ['feedback' => $this], function($message){

            $message->from('no-reply@zjxartcc.org', 'ZJX No-Reply');

            $message->to($this->controller->email);

            $message->subject('ZJX - New Feedback');

        });

    }



}

app/models/Visit.php
<?php

class Visit extends Eloquent {

    public static $RatingShort = [
        0 => 'N/A',
        1 => 'OBS', 2 => 'S1', 
        3 => 'S2', 4 => 'S3', 
        5 => 'C1', 7 => 'C3', 
        8 => 'I1', 10 => 'I3', 
        11 => 'SUP', 12 => 'ADM',
    ];

    protected $table = 'visit_requests';

    protected $fillable = array('cid', 'first_name', 'last_name', 'rating_id', 'email', 'home', 'accepted', 'reason');

	public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getRatingShortAttribute()
    {
        foreach (Visit::$RatingShort as $id => $Short) {
            if ($this->rating_id == $id) {
                return $Short;
            }
        }

        return "";
    }

    public function sendVReqDeclineEmail() {
        return Mail::send('emails.visitdeny', ['session' => $this], function($message){
            $message->to($this->email);
            $message->subject('ZJX - Visiting Application Denied');
        });
    }

    public function sendVReqUpdateEmail() {
        return Mail::send('emails.2weekvisitr', ['session' => $this], function($message){
            $message->to($this->email);
            $message->subject('ZJX - Visiting Application Update');
        });
    }

}

app/views/site/feedback/create.blade.php
@extends('layouts.master')

@section('title')
@parent
| Provide Feedback
@stop

@section('content')
<!-- Hero -->
<div class="bg-image bg-image-bottom" style="background-image: url('/assets_new/img/photos/feedback_lp_bg.png');">
	<div class="bg-primary-dark-op py-30">
		<div class="content content-full text-center">

			<!-- Header -->
			<div class="content content-center text-center">
				<div class="pt-50 pb-20">
					<h1 class="font-w700 text-white mb-10">Provide Feedback</h1>
					<h2 class="h4 font-w400 text-white-op">Jacksonville ARTCC</h2>
				</div>
				
			</div>
			<!-- END Header -->
		</div>
	</div>
</div>
<!-- END Hero -->

<!-- Breadcrumb -->
<div class="bg-body-light border-b">
	<div class="content py-5 text-center">
		<nav class="breadcrumb bg-body-light mb-0">
			<a class="breadcrumb-item" href="/">Home</a>
			<a class="breadcrumb-item" href="/feedback">Feedback</a>
			<span class="breadcrumb-item active">Provide Feedback</span>
		</nav>
	</div>
</div>
<!-- End Breadcrumb -->

	<div class="content content-full">
		<div class="row">
			<div class="col-md-12">
				<div class="block block-themed">
					<div class="block-header">
						<h3 class="block-title">Provide Feedback for a Jacksonville Controller </h3>
						
					</div>
					<div class="block-content">
						{{Form::open(['action'=>'FeedbackController@store'])}}
							<div class="row">
								<div class="col-sm-4">
									<div class="form-group">
										{{Form::label('controller_id', 'Controller:', ['class'=>'control-label'])}}
										{{Form::select('controller_id', $members, null, ['class'=>'form-control'])}}
									</div>
								</div>
								<div class="col-sm-4">
									<div class="form-group">
										{{Form::label('position', 'Position:', ['class'=>'control-label'])}}
										{{Form::select('position', Feedback::$Positions, 'JAX_CTR', ['class'=>'form-control'])}}
									</div>
								</div>
								<div class="col-sm-4">
									<div class="form-group">
										{{Form::label('level', 'Service Level', ['class'=>'control-label'])}}
										{{Form::select('level', array(
												'4' => 'Excellent', 
												'3' => 'Good', 
												'2' => 'Fair', 
												'1' => 'Poor', 
												'0' => 'Unsatisfactory'), null, ['class'=>'form-control'])}}
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-6">
									<div class="form-group">
										{{Form::label('pilot_id', 'VATSIM CID:', ['class'=>'control-label'])}}
										{{Form::text('pilot_id', null, ['class'=>'form-control'])}}
									</div>
								</div>
								<div class="col-sm-6">
									<div class="form-group">
										{{Form::label('flight_callsign', 'Flight Callsign:', ['class'=>'control-label'])}}
										{{Form::text('flight_callsign', null, ['class'=>'form-control'])}}
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-6">
									<div class="form-group">
										{{Form::label('pilot_name', 'Pilot Name:', ['class'=>'control-label'])}}
										{{Form::text('pilot_name', null, ['class'=>'form-control'])}}
									</div>
								</div>
								<div class="col-sm-6">
									<div class="form-group">
										{{Form::label('pilot_email', 'Pilot Email:', ['class'=>'control-label'])}}
										{{Form::text('pilot_email', null, ['class'=>'form-control'])}}
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-12">
									<div class="form-group">
										{{Form::label('comments', 'Comments:', ['class'=>'control-label'])}}
										{{Form::textarea('comments', null, ['class'=>'form-control'])}}
									</div> 
								</div>
							</div>
							<div class="row">
								<div class="col-sm-12">
									<div class="form-group">
										<button type="submit" class="btn btn-success">Submit</button>
									</div>
								</div>
							</div>
							{{Form::close()}}
					</div>
				</div>
			</div>
		</div>
	</div>

@stop

app/views/site/feedback/index.blade.php
@extends('layouts.master')

@section('title')
@parent
| Feedback
@stop

@section('content')

<!-- Hero -->
<div class="bg-image bg-image-bottom" style="background-image: url('/assets_new/img/photos/feedback_lp_bg.png');">
	<div class="bg-primary-dark-op py-30">
		<div class="content content-full text-center">

			<!-- Header -->
			<div class="content content-center text-center">
				<div class="pt-50 pb-20">
					<h1 class="font-w700 text-white mb-10">Feedback</h1>
					<h2 class="h4 font-w400 text-white-op">Jacksonville ARTCC</h2>
				</div>
			</div>
			<!-- END Header -->

			<!-- Actions -->
			<a href="/feedback/create" type="button" class="btn btn-rounded btn-hero btn-sm btn-success mb-5">
				<i class="fa fa-pencil mr-5"></i> Provide Feedback
			</a>
			<!-- END Actions -->
		</div>
	</div>
</div>
<!-- END Hero -->

<!-- Breadcrumb -->
<div class="bg-body-light border-b">
	<div class="content py-5 text-center">
		<nav class="breadcrumb bg-body-light mb-0">
			<a class="breadcrumb-item" href="/">Home</a>
			<span class="breadcrumb-item active">Feedback</span>
		</nav>
	</div>
</div>
<!-- End Breadcrumb -->


<div class="content content-full">
	<!-- Historical Feedback -->
	<div class="block">
		<div class="block-header block-header-default">
			<h3 class="block-title"><i class="fa fa-list mr-10"></i> Historical Feedback</h3>
		</div>
		<div class="block-content block-content-full">
			<div class="table-responsive">
			<table class="table table-bordered table-striped table-vcenter js-dataTable-full-feedback">
				<thead>
					<tr>
						<th class="text-center">Date Submitted</th>
						<th class="text-center">Controller</th>
						<th class="text-center">Controller VATSIM ID</th>
						<th class="text-center">Position</th>
						<th class="text-center">Service Rating</th>
						<th class="text-center"></th>
					</tr>
				</thead>
				<tbody>
					@forelse($feedback as $h)
							@if($h->status==1)
							<tr>
								<td class="text-center">{{{$h->created_at}}}z</td>
								<td class="text-center">{{{$h->controller->backwards_name}}}</td>
								<td class="text-center">{{{$h->controller->id}}}</td>
								<td class="text-center">{{{$h->position}}}</td>
								<td class="text-center">{{{$h->level_text}}}</td>
								<td class="text-center">
									<div class="btn-group">
										<a href="/feedback/{{$h->id}}" type="button" class="btn btn-sm btn-secondary" >
											<i class="fa fa-comments"></i>
										</a>
									</div>
								</td>
							</tr>
							@endif
							@empty
							@endforelse
				</tbody>
			</table>
			</div>
		</div>
	</div>
	<!-- END Historical Feedback -->
</div>

@stop

app/views/site/feedback/show.blade.php
@extends('layouts.master')

@section('title')
@parent
| View Feedback
@stop

@section('content')

<!-- Hero -->
<div class="bg-image bg-image-bottom" style="background-image: url('/assets_new/img/photos/feedback_lp_bg.png');">
	<div class="bg-primary-dark-op py-30">
		<div class="content content-full text-center">

			<!-- Header -->
			<div class="content content-center text-center">
				<div class="pt-50 pb-20">
					<h1 class="font-w700 text-white mb-10">View Feedback</h1>
					<h2 class="h4 font-w400 text-white-op">Jacksonville ARTCC</h2>
				</div>
				
			</div>
			<!-- END Header -->
		</div>
	</div>
</div>
<!-- END Hero -->

<!-- Breadcrumb -->
<div class="bg-body-light border-b">
	<div class="content py-5 text-center">
		<nav class="breadcrumb bg-body-light mb-0">
			<a class="breadcrumb-item" href="/">Home</a>
			<a class="breadcrumb-item" href="/feedback">Feedback</a>
			<span class="breadcrumb-item active">View Feedback</span>
		</nav>
	</div>
</div>
<!-- End Breadcrumb -->

@if($f)
	<div class="content content-full">
		<div class="row">
			<div class="col-md-12">
				<div class="block block-themed">
					<div class="block-header">
						<h3 class="block-title">Pilot Feedback for {{{$f->controller->full_name}}} (ID: {{$f->id}}) </h3>
						
					</div>
					<div class="block-content">
						@if(Auth::check())
							@if(Auth::user()->can('snrstaff') || Auth::user()->can('instruct'))
							<p><b>Submitter:</b> {{$f->pilot_name}} ({{$f->pilot_id}}) flying as {{$f->flight_callsign}}</p>
							@endif
						@endif
						<p><b>Date:</b> {{$f->created_at}}z</p>
						<p><b>Service Rating:</b> {{$f->level_text}}</p>
					 	<p><b>Controller's Name:</b> {{{$f->controller->full_name}}}</p>
					 	<p><b>Controller's VATSIM ID:</b> {{{$f->controller->id}}}</p>
					 	<p><b>Controller's Position:</b> {{$f->position}}</p>
						<p><b>Feedback:</b> {{$f->comments}}</p>
					</div>
				</div>
			</div>
		</div>
	</div>
@else
	<!-- Page Content -->
	<div class="content content-full">
		<div class="hero-inner">
			<div class="content content-full">
				<div class="py-30 text-center">
					<div class="display-3 text-danger">
						<i class="fa fa-warning"></i> Feedback Error
					</div>
					<h1 class="h2 font-w700 mt-30 mb-10">You just found an error page!</h1>
					<h2 class="h3 font-w400 text-muted mb-50">We are sorry. The feedback you are looking for was not found.</h2>
					<a class="btn btn-hero btn-rounded btn-alt-secondary" href="/">
						<i class="fa fa-arrow-left mr-10"></i> Back to Homepage
					</a>
				</div>
			</div>
		</div>
	</div>
	<!-- END Page Content -->
@endif

@stop