app/models/Exam.php
<?php

class Exam extends Eloquent {

	public static $AssExam = [
        1 => 'Major Delivery',
        2 => 'Major Ground', 
        3 => 'Major Tower', 
        4 => 'Major Approach',
        ];

    protected $table = 'training_assigned_exams';

    protected $fillable = array('controller_id', 'exam_id', 'instructor_id', 'complete');


    public function controller() {
        return $this->hasOne('User', 'id', 'controller_id');
    }

    public function instructor() {
        return $this->hasOne('User', 'id', 'instructor_id');
    }

    public function getAssExamAttribute()
    {
        foreach (Exam::$AssExam as $id => $exam) {
            if ($this->exam_id == $id) {
                return $exam;
            }
        }

        return "";
    }

    public function getPassRateAttribute()
    {
        switch($this->passed)
        {
            case 0: return "Failed";
            case 1: return "Passed";
        }
    }

}

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Zizaco\Entrust\HasRole;


class User extends Eloquent implements UserInterface {
    use UserTrait;
    use HasRole;

    public static $RatingShort = [
        0 => 'N/A',
        1 => 'OBS', 2 => 'S1', 
        3 => 'S2', 4 => 'S3', 
        5 => 'C1', 7 => 'C3', 
        8 => 'I1', 10 => 'I3', 
        11 => 'SUP', 12 => 'ADM',
    ];

    public $timestamps = true;

    public static $RatingLong = [
        0 => 'Pilot',
        1 => 'Pilot/Observer', 2 => 'Student 1', 
        3 => 'Student 2', 4 => 'Student 3', 
        5 => 'Controller 1', 7 => 'Controller 3', 
        8 => 'Instructor 1', 10 => 'Instructor 3', 
        11 => 'Supervisor', 12 => 'Administrator',
    ];

    public static $StaffRoleToSMFGroup = [
        '0' => '20',
        '1' => '9',
        '2' => '10',
        '3' => '11',
        '4' => '12',
        '5' => '13',
        '6' => '14',
        '7' => '15',
        '8' => '16',
        '9' => '17',
        '12' => '9',
        '13'=> '22',
    ];

    public static $TrainingRoleToSMFGroup = [
        '0' => '',
        '10' => '18',
        '11' => '19',
    ];

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'roster';

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = array('password', 'remember_token');

    protected $fillable = array('id', 'first_name', 'last_name', 'email', 'rating_id', 'canTrain', 'visitor', 'visitor_from', 'status', 'loa', 'del', 'gnd', 'twr', 'app', 'ctr');

    public function controller_log() {
        $this->hasMany('ControllerLog', 'cid');
    }

    public function getFullNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function getBackwardsNameAttribute()
    {
        return $this->last_name . ", " . $this->first_name;
    }

    public function getRatingShortAttribute()
    {
        foreach (User::$RatingShort as $id => $Short) {
            if ($this->rating_id == $id) {
                return $Short;
            }
        }

        return "";
    }

    public function getRatingLongAttribute()
    {
        foreach (User::$RatingLong as $id => $Long) {
            if ($this->rating_id == $id) {
                return $Long;
            }
        }

        return "";
    }

    public function getLocalHoursAttribute()
    {
        $duration = DB::table('controller_log')->where('cid', $this->id)
            ->where(function($query){
                $query->where('position', 'LIKE', '%_DEL')
                      ->orWhere('position', 'LIKE', '%_GND')
                      ->orWhere('position', 'LIKE', '%_TWR');
            })
            ->whereRaw("date_format(STR_TO_DATE(`date`, '%m/%d/%Y'), '%m/%Y') = date_format(now(), '%m/%Y')")
            ->sum('duration'); 

        if(!$duration == 0) {
            $hours = $duration / 3600;
            return number_format($hours, 2);
        } else {
            return '--';
        }
    }

    public function getApproachHoursAttribute()
    {
        $duration = DB::table('controller_log')
            ->where('cid', $this->id)
            ->where('position', 'LIKE', '%_APP')
            ->whereRaw("date_format(STR_TO_DATE(`date`, '%m/%d/%Y'), '%m/%Y') = date_format(now(), '%m/%Y')")
            ->sum('duration');

        if(!$duration == 0) {
            $hours = $duration / 3600;
            return number_format($hours, 2);
        } else {
            return '--';
        }
    }

    public function getCenterHoursAttribute()
    {
        $duration = DB::table('controller_log')
            ->where('cid', $this->id)
            ->where('position', 'LIKE', '%_CTR')
            ->whereRaw("date_format(STR_TO_DATE(`date`, '%m/%d/%Y'), '%m/%Y') = date_format(now(), '%m/%Y')")
            ->sum('duration');

        if(!$duration == 0) {
            $hours = $duration / 3600;
            return number_format($hours, 2);
        } else {
            return '--';
        }
    }

    public function getTotalHoursAttribute()
    {
        $duration = DB::table('controller_log')
            ->where('cid', $this->id)
            ->whereRaw("date_format(STR_TO_DATE(`date`, '%m/%d/%Y'), '%m/%Y') = date_format(now(), '%m/%Y')")
            ->sum('duration');
        
        if(!$duration == 0) {
            $hours = $duration / 3600;
            return number_format($hours, 2);
        } else {
            return '--';
        }
    }

    public function getStaffLongAttribute()
    {
        switch($this->staff_role)
        {
            case 'ATM': return "Air Traffic Manager";
            case 'DATM': return "Deputy Air Traffic Manager";
            case 'TA': return "Training Administrator";
            case 'WM': return "Webmaster";
            case 'FE': return "Facility Engineer";
            case 'EC': return "Events Coordinator";
            case 'ATA': return "Assistant Training Administrator";
            case 'AEC': return "Assistant Events Coordinator";
            case 'AWM': return "Assistant Webmaster";

        }
    }

    public function getDelCertAttribute()
    {
        switch($this->del)
        {
            case 0: return "No Certification";
            case 1: return "Minor Training";
            case 2: return "Minor Certified";
            case 3: return "Major Training";
            case 4: return "Major Certified";

        }
    }

    public function getGndCertAttribute()
    {
        switch($this->gnd)
        {
            case 0: return "No Certification";
            case 1: return "Minor Training";
            case 2: return "Minor Certified";
            case 3: return "Major Training";
            case 4: return "Major Certified";

        }
    }

    public function getTwrCertAttribute()
    {
        switch($this->twr)
        {
            case 0: return "No Certification";
            case 1: return "Minor Training";
            case 2: return "Minor Certified";
            case 3: return "Major Training";
            case 4: return "Major Certified";

        }
    }

    public function getAppCertAttribute()
    {
        switch($this->app)
        {
            case 0: return "No Certification";
            case 1: return "Minor Training";
            case 2: return "Minor Certified";
            case 3: return "Major Training";
            case 4: return "Major Certified";

        }
    }

    public function getCtrCertAttribute()
    {
        switch($this->ctr)
        {
            case 0: return "No Certification";
            case 1: return "Training";
            case 2: return "Certified";

        }
    }

    public function createSMFMember()
    {
        require_once(Config::get('services.smf.path') . "/smf_2_api.php");

        $registration_options = [
            'member_name' => $this->id,
            'email' => $this->email,
            'real_name' => $this->full_name,
            'password' => uniqid(),
            'require' => 'nothing', // No known password is required
            'id_group' => $this->visitor === 1 ? '20' : '19',
        ];

        $result = smfapi_registerMember($registration_options);

        if (is_array($result))
            throw new \Exception("Error attempting to register smf member: " . var_export($result, true));
    }

    /*
     * CAUTION:
     * Only call this method when the user has been properly authenticated.
     * This will log them into an smf session regardless of currently laravel session.
     */
    public function loginToSMF()
    {
        require_once(Config::get('services.smf.path') . "/smf_2_api.php");

        smfapi_login($this->id);

        setcookie("ids_loggedin", $this->id, 0, "", ".zjxartcc.org");
        $_SESSION['loggedin'] = $this->id;
    }

    /*
     * Only call this method when the user has been properly authenticated.
     * This will log them into an smf session regardless of currently laravel session.
     */
    public function logoutOfSMF()
    {
        require_once(Config::get('services.smf.path') . "/smf_2_api.php");

        // We don't care if the logout failed
        smfapi_logout($this->id);
    }

    public function sendVReqDeclineEmail() {
        return Mail::send('emails.visitdeny', ['session' => $this], function($message){
            $message->to($this->visitr->email);
            $message->subject('ZJX - Visiting Application Denied');
        });
    }

    public function sendVReqUpdateEmail() {
        return Mail::send('emails.2weekvisitr', ['session' => $this], function($message){
            $message->to($this->visitr->email);
            $message->subject('ZJX - Visiting Application Update');
        });
    }

    public function hasStaff()
    {
        if($this->hasRole('ATM') || $this->hasRole('DATM') || $this->hasRole('TA') || $this->hasRole('WM') || $this->hasRole('ATA') || $this->hasRole('AEC') || $this->hasRole('EC') || $this->hasRole('FE') || $this->hasRole('AWM')) {
            return true;
        } else {
            return false;
        }
    }

    public function hasTrainingStaff()
    {
        if($this->hasRole('INS') || $this->hasRole('MTR')) {
            return true;
        } else {
            return false;
        }
    }

    public function userFirstStaff()
    {
        $assignedrole = DB::table(Config::get('entrust::assigned_roles_table'))->where('user_id', $this->id)->first();
        $role = DB::table(Config::get('entrust::roles_table'))->where('id', $assignedrole->role_id)->first();
        return $role->name;
    }

    public function siteActivity()
    {
    	return $this->hasMany('ActivityLog', 'user_id', 'id')->orderBy('id', 'DESC')->first();
    }

    public function controlActivity()
    {
    	return $this->hasMany('ControllerLog', 'cid', 'id')->orderBy('id', 'DESC')->first();
    }
    
    public function quarterlyHours($quarter,$year)
    {

app/controllers/MentorController.php
<?php

use Carbon\Carbon;

class MentorController extends BaseController {

	public function showRequests()
	{
		$sessions = MentorAvail::where('trainee_id', '!=', 0)->where('slot', '>', new Carbon('midnight today', 'America/New_York'))->orderBy('slot', 'ASC')->get();
		return View::make('admin.mentors.sessions')->with('sessions', $sessions);
	}

	public function findStudents()
	{
		$user = User::where('status', '0')->orderBy('last_name', 'ASC')->get()->lists('backwards_name', 'id');
		return View::make('admin.mentors.studentsearch')->with('user', $user);
	}

	public function findStudent()
	{
		$id = Input::get('controller');
		return Redirect::to('/admin/mentor/student/'.$id);
	}

	public function student($id)
	{
		$user = User::find($id);
		$note = TrainingNote::where('controller_id', '=', $id)->orderBy('date', 'DESC')->orderBy('session_begin', 'DESC')->get();
		$exam = json_decode(file_get_contents("https://api.vatusa.net/v2/user/".$id."/exam/history?apikey=ef9SEgwK6Z0bCDPp"),true);
		return View::make('admin.mentors.student')->with('user', $user)->with('note', $note)->with('exam', $exam);
	}

	public function showNote($id)
	{
		$note = TrainingNote::find($id);
		return View::make('admin.mentors.note')->with('note', $note);
	}

	public function addNote()
	{
		$user = User::where('status', 0)->orderBy('last_name', 'ASC')->get()->lists('backwards_name', 'id');
		return View::make('admin.mentors.addnote')->with('user', $user);
	}

	public function saveNote()
	{
		$description = Input::get('comments');
		$desc = nl2br(htmlentities($description, ENT_QUOTES, 'UTF-8'));

		TrainingNote::create([
			'controller_id'=>Input::get('controller_id'),
        	'instructor_id'=>Auth::id(),
        	'position'=>Input::get('position'),
        	'type'=>Input::get('type'),
        	'comments'=>$desc,
        	'date'=>Input::get('date'),
        	'session_begin'=>Input::get('session_begin'),
        	'duration'=>Input::get('duration')
		]);

		ActivityLog::create(['note' => 'Added Training Note for: '.Input::get('controller_id') .' on '. Input::get('position'), 'user_id' => Auth::id(), 'log_state' => 1, 'log_type' => 8]);
		
		return Redirect::to('/admin/mentor/addnote')->with('message', 'Training Note Created!');
	}

	public function recOTS()
	{
		$user = User::where('status', '0')->orderBy('last_name', 'ASC')->get()->lists('full_name', 'id');
		return View::make('admin.mentors.recots')->with('user', $user);
	}

	public function saveOTSReq()
	{
		OTSRequest::create([
			'controller_id'=>Input::get('controller'),
        	'position'=>Input::get('position'),
        	'requested_by'=>Auth::id()
		]);

		ActivityLog::create(['note' => Input::get('controller_id') .' suggested for OTS on '. Input::get('position'), 'user_id' => Auth::id(), 'log_state' => 1, 'log_type' => 8]);
		
		return Redirect::to('/admin/mentor/otsrec')->with('message', 'Controller submitted for OTS/Validation!');
	}

	public function cancelSession($id)
	{
		$request = MentorAvail::find($id);
		$request->cancel_message = Input::get('cancel');
		$request->save();
		$request->sendCancellationEmail();
		$request->delete();

		ActivityLog::create(['note' => 'Cancelled Session: '.$request->slot, 'user_id' => Auth::id(), 'log_state' => 3, 'log_type' => 6]);

		return Redirect::to('/admin/mentor/requests')->with('message', 'Session canceled. Student has been notified!');
	}

	public function showChecklists()
	{
		return View::make('admin.mentors.checklists');
	}

	public function showAvail()
	{
		$availability = MentorAvail::where('mentor_id', '=', Auth::id())->get();
		return View::make('admin.mentors.mentoravail')->with('availability', $availability);
	}

	public function postAvail()
	{
		$mentor_id = Auth::id();
		$slots = Input::get('slots');
		$today = new Carbon("midnight today", 'America/New_York');

		$availability = MentorAvail::where('mentor_id', '=', $mentor_id)->where('slot', '>=', $today)->get();

		if (!$slots) $slots = [];

		// Slots to be added
		$new_slots = array_diff($slots, $availability->lists('slot'));
		// Slots to be deleted
		$old_slots = array_diff($availability->lists('slot'), $slots);

		foreach ($new_slots as $slot) {
			MentorAvail::create([
				'mentor_id' => $mentor_id,
				'slot' => $slot,
			]);
		}

		MentorAvail::where('mentor_id', '=', $mentor_id)->whereIn('slot', $old_slots)->delete();
		ActivityLog::create(['note' => 'Updated Availability', 'user_id' => Auth::id(), 'log_state' => 2, 'log_type' => 6]);

		return Redirect::action('MentorController@showAvail')->with('message', 'Availability has been updated');
	}

}

app/views/admin/mentors/addnote.blade.old.php
@extends('layouts.master')

@section('title')
@parent
| Instructing
@stop

@section('content')

<div class="page-heading-two">
    <div class="container">
        <h2>Admin - Instructing - Add Training Note</h2>
    </div>
</div>

<div class="container">
	{{ Form::open(['action' => 'MentorController@saveNote']) }}
		<div class="row">
			<div class="col-sm-4">
				<div class="form-group">
       			    {{Form::label('controller_id', 'Controller:', ['class'=>'control-label'])}}
                    {{Form::select('controller_id', $user, null, ['class'=>'form-control'])}}
       			</div>
       		</div>
       		<div class="col-sm-4">
       			<div class="form-group">
		       		{{Form::label('position', 'Position:', ['class'=>'control-label'])}}
		            {{Form::select('position', TrainingNote::$SesPos, 1, ['class'=>'form-control'])}}
		       	</div>
		    </div>
		    <div class="col-sm-4">
       			<div class="form-group">
		       		{{Form::label('type', 'Session Type:', ['class'=>'control-label'])}}
		            {{Form::select('type', TrainingNote::$SesType, 1, ['class'=>'form-control'])}}
		       	</div>
		    </div>
		</div>
		<div class="row">
			<div class="col-sm-4">
				<div class="form-group">
		       		{{Form::label('date', 'Date:', ['class'=>'control-label'])}}
			       		<div class="input-group date" id="date">
			       		{{Form::text('date', null, ['class'=>'form-control'])}}
			       		<span class="input-group-addon">
			       			<i class="fa fa-calendar"></i>
		       			</span>
		       		</div>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="form-group">
		       		{{Form::label('session_begin', 'Start Time:', ['class'=>'control-label'])}}
		            {{Form::select('session_begin', TrainingNote::$TimeStart, 1, ['class'=>'form-control'])}}
		        </div>
			</div>
			<div class="col-sm-4">
				<div class="form-group">
		       		{{Form::label('duration', 'Duration (mins):', ['class'=>'control-label'])}}
		            {{Form::text('duration', null, ['class'=>'form-control'])}}
		        </div>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-12">
				<div class="form-group">
		       		{{Form::label('comments', 'Comments and Notes:', ['class'=>'control-label'])}}
		            {{Form::textarea('comments', null, ['class'=>'form-control'])}}
		        </div>
			</div>
		</div>

       	<div class="row">
       		<div class="col-sm-12">
       			<div class="form-group">
 	      			{{Form::submit('Submit', ['class' => 'btn btn-primary'])}}
       			</div>
       		</div>
       	</div>
	{{ Form::close() }}
</div>

		<script>
            $(function () {
            	var dtpOptions = {
                	icons: {
	                    time: "fa fa-clock-o",
	                    date: "fa fa-calendar",
	                    up: "fa fa-arrow-up",
	                    down: "fa fa-arrow-down"
	                },
	                format: 'YYYY-MM-DD'
                };

                $('#date').datetimepicker(dtpOptions);
                
                $('#date').on('dp.change', function(e) {
                	$("#date").data('DateTimePicker').maxDate(e.date);
                });
            });
        </script>

@stop

app/views/admin/mentors/note.blade.old.php
@extends('layouts.master')

@section('title')
@parent
| Training
@stop

@section('content')

<div class="page-heading-two">
    <div class="container">
        <h2>Training - Training Note</h2>
    </div>
</div>

@if($note)
    <div class="container">
        <div class="row">   
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">Training Note for {{$note->controller->full_name}} on {{$note->ses_pos}}, {{$note->date}} at {{$note->session_begin}}z</h4>
                    </div>
                    <div class="panel-body">
                        <p><b>Training Type:</b> {{$note->ses_type}}</p>
                        <p><b>Duration:</b> {{$note->duration}} with {{$note->instructor->full_name}}</p>
                        <p><b>Comments:</b></p>
                        {{$note->comments}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@else
    <div class="container">
        <div class="row">   
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h4><b>NO TRAINING NOTE FOUND</b></h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endif

@stop

app/views/admin/mentors/student.blade.old.php
@extends('layouts.master')

@section('title')
@parent
| Instructing
@stop

@section('content')

<div class="page-heading-two">
    <div class="container">
        <h2>Admin - Instructing - Student Notes</h2>
    </div>
</div>
	
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<h4>{{{$user->full_name}}} - {{{$user->rating_long}}}</h4>
		</div>
	</div>
	<div class="row">	
		<div class="col-sm-3">
			<div class="table-responsive">
                <table class="table table-bordered">
                    <tr>
                        <th width="40%">Delivery</th>
                        <th width="60%">{{{$user->del_cert}}}</th>
                    </tr>
                    <tr>
                        <th width="40%">Ground</th>
                        <th width="60%">{{{$user->gnd_cert}}}</th>
                    </tr>
                    <tr>
                        <th width="40%">Tower</th>
                        <th width="60%">{{{$user->twr_cert}}}</th>
                    </tr>
                    <tr>
                        <th width="40%">Approach</th>
                        <th width="60%">{{{$user->app_cert}}}</th>
                    </tr>
                    <tr>
                        <th width="40%">Center</th>
                        <th width="60%">{{{$user->ctr_cert}}}</th>
                    </tr>
				</table>
            </div>
		</div>
		<div class="col-sm-9">
			<ul class="nav nav-tabs nav-justified">
				<li class="active"><a data-toggle="tab" href="#notes">Training Notes</a></li>
		  		<li><a data-toggle="tab" href="#exams">Exams</a></li>
	  		</ul>
	  		<div class="tab-content">
		    	<div id="notes" class="tab-pane fade-in active">
			        <div class="table-responsive">
	                <table class="table table-bordered">
		                <thead>    
		                    <tr>
		                        <th width="20%">Date</th>
		                        <th width="15%">Position</th>
		                        <th width="20%">Instructor</th>
		                        <th width="15%">Type</th>
		                        <th width="10%">Actions</th>
		                    </tr>
		                </thead>
		                <tbody>
		                	@forelse($note as $n)
		                	<tr>
		                		<td>{{{$n->date}}} - {{{$n->session_begin}}}</td>
		                		<td>{{{$n->ses_pos}}}</td>
		                		<td>{{{$n->instructor->full_name}}}</td>
		                		<td>{{{$n->ses_type}}}</td>
		                		<td><a href="/admin/mentor/note/{{{$n->id}}}" class="btn btn-success btn-sm simple-tooltip" title="View Details"><i class="fa fa-info-circle"></i></a></td>
		                	</tr>
		                	@empty
		                	<tr>
		                		<td colspan="6"><center>No Session Notes Available</center></td>
		                	</tr>
		                	@endforelse
		                </tbody>
					</table>
            		</div>
				</div>
				<div id="exams" class="tab-pane fade-in">
			        <div class="table-responsive">
	                <table class="table table-bordered">
		                <thead>    
		                    <tr>
		                        <th width="25%">Exam Assigned</th>
								<th width="25%">Assigned By</th>
								<th width="30%">Assigned On</th>
								<th width="20%">Passed?</th>
		                    </tr>
		                </thead>
		                <tbody>
		                	@forelse($exam as $e)
			                	@if($e->complete == 1)
			                	<tr>
									<td>{{{$e->ass_exam}}}</td>
									<td>{{{$e->instructor->full_name}}}</td>
									<td>{{{$e->created_at}}}</td>
									<td>{{{$e->pass_rate}}}</td>
								</tr>
								@elseif($e->complete == 0)
								<tr>
									<td>{{{$e->ass_exam}}}</td>
									<td>{{{$e->instructor->full_name}}}</td>
									<td>{{{$e->created_at}}}</td>
									<td>Not Yet Taken</td>
								</tr>
								@endif
		                	@empty
		                	<tr>
		                		<td colspan="4"><center>No Exam History Available</center></td>
		                	</tr>
		                	@endforelse
		                </tbody>
					</table>
            		</div>
				</div>
			</div>
		</div>
	</div>
</div>

@stop

app/views/admin/mentors/studentsearch.blade.old.php
@extends('layouts.master')

@section('title')
@parent
| Instructing
@stop

@section('content')

<div class="page-heading-two">
    <div class="container">
        <h2>Admin - Instructing - Search Student</h2>
    </div>
</div>

<div class="container">
	{{ Form::open(['action' => 'MentorController@findStudent']) }}
		<div class="row">
			<div class="col-sm-12">
				<div class="form-group">
       			    {{Form::label('controller', 'Controller:', ['class'=>'control-label'])}}
                	{{Form::select('controller', $user, null, ['class'=>'form-control'])}}
       			</div>
       			<div class="form-group">
 	      			{{Form::submit('Submit', ['class' => 'btn btn-primary'])}}
       			</div>
			</div>
		</div>
	{{ Form::close() }}
</div>

@stop